version: "3.8"

networks:
  local_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

services:

  postgresql:
    image: postgres
    container_name: postgresql

    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sistema_vendas
    ports:
      - "5432:5432"
    networks:
      local_net:
        ipv4_address: 192.168.1.2

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4

    volumes:
      - ./data/pgamin-data:/var/lib/pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      local_net:
        ipv4_address: 192.168.1.3
    ports:
      - "5050:80"


  # Observability

  grafana:
    image: grafana/grafana:8.2.3
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"


